openapi: 3.0.3
info:
  title: API服务的接口文档
  description: |-
    本人开发的API服务，功能还在不断完善中，欢迎使用。此处为各个功能的接口说明文档。您还可以访问
    <a href="https://apifox.com/apidoc/shared-c060f0ae-ed4a-41e6-94e9-e00418dda36b" target="_blank">Apifox版本的API文档</a>得到更好的阅读体验，并进行在线调试。
  version: 1.0.0
paths:
  /uniapp-service/register:
    post:
      summary: 用户注册
      deprecated: false
      description: ''
      operationId: registerUsingPOST
      tags:
        - 用户管理
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: sk-12345678abcdefg
          schema:
            type: string
            default: sk-12345678abcdefg
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterDTO'
            example: ''
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Result%C2%ABUserRegisterVO%C2%BB'
          headers: {}
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /uniapp-service/api/idcard/addBg:
    post:
      summary: 生成身份证照片
      deprecated: false
      description: ''
      operationId: getIDPhotoUsingPOST
      tags:
        - 身份证服务     
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IDCardDto'
            example: ''
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Result%C2%ABIDCardVO%C2%BB'
          headers: {}
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
  /uniapp-service/api/name/analysis:
    post:
      summary: 姓名解析
      deprecated: false
      description: ''
      operationId: analysisUsingPOST
      tags:
        - 姓名解析服务
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: sk-12345678abcdefg
          schema:
            type: string
            default: sk-12345678abcdefg
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NameAnalysisDto'
            example: ''
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Result%C2%ABNameAnalysisVO%C2%BB'
          headers: {}
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
  /uniapp-service/api/runway/add:
    post:
      summary: 发起新任务
      deprecated: false
      description: ''
      operationId: addUsingPOST_4
      tags:
        - Runway任务管理
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: sk-12345678abcdefg
          schema:
            type: string
            default: sk-12345678abcdefg
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRunwayTaskDTO'
            example: ''
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema: &ref_0
                $ref: '#/components/schemas/Result%C2%ABRunwayTaskVO%C2%BB'
          headers: {}
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
      
  /uniapp-service/api/runway/getTask:
    get:
      summary: 获取任务信息
      deprecated: false
      description: ''
      operationId: getTaskUsingGET
      tags:
        - Runway任务管理
      parameters:
        - name: taskId
          in: query
          description: taskId
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          example: sk-12345678abcdefg
          schema:
            type: string
            default: sk-12345678abcdefg
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema: *ref_0
          headers: {}
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
      
components:
  schemas:
    Result«UserRegisterVO»:
      title: Result«UserRegisterVO»
      required:
        - code
        - success
      type: object
      properties:
        code:
          type: integer
          description: 返回结果状态码，0为成功，非0为失败
          format: int32
          examples:
            - 0
        message:
          type: string
          description: 返回结果说明信息
          examples:
            - 执行成功
        result:
          description: 返回结果数据
          $ref: '#/components/schemas/UserRegisterVO'
        success:
          type: boolean
          description: 是否成功标志
          examples:
            - true
        timestamp:
          type: integer
          description: 返回的时间戳
          format: int64
      description: 接口调用返回结果
    UserRegisterVO:
      title: UserRegisterVO
      required:
        - apiKey
        - loginName
      type: object
      properties:
        apiKey:
          type: string
          description: API密钥
          examples:
            - sk-123456
        birthYear:
          type: integer
          description: 出生年份
          format: int32
          examples:
            - 2000
        createdTime:
          type: string
          description: 创建时间
          format: date-time
        email:
          type: string
          description: 电子邮箱
          examples:
            - hello@gmail.com
        headerImgPath:
          type: string
          description: 头像地址
          examples:
            - http://baidu.com
        lastLoginTime:
          type: string
          description: 最后登录时间
          format: date-time
        loginName:
          type: string
          description: 登录账号
          examples:
            - hello
        modifiedTime:
          type: string
          description: 创建时间
          format: date-time
        phone:
          type: string
          description: 电话号码
          examples:
            - '18573294999'
        sex:
          type: integer
          description: 性别：0-未知/1-男/2-女，默认值为0
          format: int32
          examples:
            - 1
      description: 用户注册信息
    UserRegisterDTO:
      title: UserRegisterDTO
      required:
        - loginName
        - pwd
      type: object
      properties:
        birthYear:
          type: integer
          description: 出生年份
          format: int32
          examples:
            - 2000
        email:
          type: string
          description: 电子邮箱
          examples:
            - hello@gmail.com
        headerImgPath:
          type: string
          description: 头像地址
          examples:
            - http://baidu.com
        loginName:
          type: string
          description: 登录账号
          examples:
            - hello
        phone:
          type: string
          description: 电话号码
          examples:
            - '18573294999'
        pwd:
          type: string
          description: 登录密码
          examples:
            - hello
        sex:
          type: integer
          description: 性别：0-未知/1-男/2-女，默认值为0
          format: int32
          examples:
            - 1
      description: 用户注册参数
    AddRunwayTaskDTO:
      title: AddRunwayTaskDTO
      required:
        - images
        - ratio
        - seconds
        - taskType
      type: object
      properties:
        callbackUrl:
          type: string
          description: 回调通知地址
          examples:
            - http://baidu.com
        images:
          type: array
          description: 图片资源信息
          items:
            $ref: '#/components/schemas/AddRunwayTaskImageDTO'
        ratio:
          type: string
          description: 图片宽度与高度之比，16:9,9:16
          examples:
            - '16:9'
        seconds:
          type: integer
          description: 视频时长，5 或 10
          format: int32
          examples:
            - 10
        taskType:
          type: string
          description: 任务类型，gen3a_turbo,gen3a,gen2
          examples:
            - gen3a_turbo
        textPrompt:
          maxLength: 2000
          minLength: 0
          type: string
          description: 提示词
      description: 添加Runway任务参数
    AddRunwayTaskImageDTO:
      title: AddRunwayTaskImageDTO
      required:
        - image
      type: object
      properties:
        frameIndex:
          type: integer
          description: 图片索引，第一张为0，最后一张为1
          format: int32
          examples:
            - 0
        image:
          type: string
          description: 图片地址
          examples:
            - http://baidu.com
      description: 添加Runway任务参数之图片
    IDCardDto:
      title: IDCardDto
      required:
        - base64
      type: object
      properties:
        base64:
          type: string
        bgColor:
          type: string
        dpi:
          type: integer
          format: int32
        faceAlignment:
          type: boolean
        faceDetectModel:
          type: string
        hd:
          type: boolean
        headHeightRatio:
          type: number
          format: float
        headMeasureRatio:
          type: number
          format: float
        humanMattingModel:
          type: string
        kb:
          type: integer
          format: int32
        render:
          type: integer
          format: int32
        resize:
          type: integer
          format: int32
        targetHeight:
          type: integer
          format: int32
        targetWidth:
          type: integer
          format: int32
        topDistanceMax:
          type: number
          format: float
        topDistanceMin:
          type: number
          format: float
    IDCardVO:
      title: IDCardVO
      type: object
      properties:
        data:
          type: string
        imageBytes:
          type: string
          format: byte
    NameAnalysisDto:
      title: NameAnalysisDto
      required:
        - lastname
        - surname
      type: object
      properties:
        lastname:
          type: string
        surname:
          type: string
    NameAnalysisVO:
      title: NameAnalysisVO
      type: object
      properties:
        fiveDetailHtml:
          type: string
        tableHtml:
          type: string
        totalEvaluate:
          type: string
        totalScore:
          type: string
    Result«IDCardVO»:
      title: Result«IDCardVO»
      required:
        - code
        - success
      type: object
      properties:
        code:
          type: integer
          description: 返回结果状态码，0为成功，非0为失败
          format: int32
          examples:
            - 0
        message:
          type: string
          description: 返回结果说明信息
          examples:
            - 执行成功
        result:
          description: 返回结果数据
          $ref: '#/components/schemas/IDCardVO'
        success:
          type: boolean
          description: 是否成功标志
          examples:
            - true
        timestamp:
          type: integer
          description: 返回的时间戳
          format: int64
      description: 接口调用返回结果
    Result«NameAnalysisVO»:
      title: Result«NameAnalysisVO»
      required:
        - code
        - success
      type: object
      properties:
        code:
          type: integer
          description: 返回结果状态码，0为成功，非0为失败
          format: int32
          examples:
            - 0
        message:
          type: string
          description: 返回结果说明信息
          examples:
            - 执行成功
        result:
          description: 返回结果数据
          $ref: '#/components/schemas/NameAnalysisVO'
        success:
          type: boolean
          description: 是否成功标志
          examples:
            - true
        timestamp:
          type: integer
          description: 返回的时间戳
          format: int64
      description: 接口调用返回结果
    Result«RunwayTaskVO»:
      title: Result«RunwayTaskVO»
      required:
        - code
        - success
      type: object
      properties:
        code:
          type: integer
          description: 返回结果状态码，0为成功，非0为失败
          format: int32
          examples:
            - 0
        message:
          type: string
          description: 返回结果说明信息
          examples:
            - 执行成功
        result:
          description: 返回结果数据
          $ref: '#/components/schemas/RunwayTaskVO'
        success:
          type: boolean
          description: 是否成功标志
          examples:
            - true
        timestamp:
          type: integer
          description: 返回的时间戳
          format: int64
      description: 接口调用返回结果
    RunwayTaskVO:
      title: RunwayTaskVO
      required:
        - id
        - images
        - ratio
        - seconds
        - taskStatusCode
        - taskType
      type: object
      properties:
        callbackUrl:
          type: string
          description: 回调通知地址
          examples:
            - http://baidu.com
        createdTime:
          type: string
          description: 创建时间
          examples:
            - yyyy-MM-dd HH:mm:ss
        error:
          type: string
          description: 错误信息
        id:
          type: string
          description: Runway任务ID
          examples:
            - '123456'
        images:
          type: array
          description: 图片资源信息
          items:
            $ref: '#/components/schemas/RunwayTaskImageVO'
        modifiedTime:
          type: string
          description: 修改时间
          examples:
            - yyyy-MM-dd HH:mm:ss
        ratio:
          type: string
          description: 图片宽度与高度之比，16:9,9:16
          examples:
            - '16:9'
        seconds:
          type: integer
          description: 视频时长，5 或 10
          format: int32
          examples:
            - 10
        taskStatusCode:
          type: integer
          description: 任务状态，0：新增；1：排队中；2：视频制作中；3：视频制作成功；4：视频制作失败
          format: int32
          examples:
            - 0
        taskType:
          type: string
          description: 任务类型，gen3a_turbo,gen3a,gen2
          examples:
            - gen3a_turbo
        textPrompt:
          type: string
          description: 提示词
          examples:
            - fly
        videoUrl:
          type: string
          description: 视频下载地址
          examples:
            - http://baidu.com
      description: Runway任务信息
    RunwayTaskImageVO:
      title: RunwayTaskImageVO
      required:
        - imageActual
        - imageOrg
        - taskId
      type: object
      properties:
        createdTime:
          type: string
          description: 创建时间
          examples:
            - yyyy-MM-dd HH:mm:ss
        frameIndex:
          type: integer
          description: 图片索引，第一张为0，最后一张为1
          format: int32
          examples:
            - 0
        imageActual:
          type: string
          description: 实际上传的图片地址
        imageOrg:
          type: string
          description: 原始图片地址
        modifiedTime:
          type: string
          description: 修改时间
          examples:
            - yyyy-MM-dd HH:mm:ss
        taskId:
          type: string
          description: Runway任务ID
          examples:
            - '123456'
      description: Runway任务资源信息
  securitySchemes: 
    请求头参数API-KEY:
      type: apiKey
      name: Authentication
      in: header
      description: |-
        用户注册成功后，系统会生成一个apikey，用户需要将该apikey添加到请求头中，格式类似 sk-12345678abcdefg。
security:
  - 请求头参数API-KEY: []
servers:
  - url: https://api.qimuinfo.top
    description: 正式环境
